/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import 'stencil-apexcharts';


export namespace Components {

  interface AppCombobox {
    'combodata': string[];
    'comboid': string;
    'componentWidth': string;
    'selectedData': string;
  }
  interface AppComboboxAttributes extends StencilHTMLAttributes {
    'combodata'?: string[];
    'comboid'?: string;
    'componentWidth'?: string;
    'onEntitySelected'?: (event: CustomEvent) => void;
    'selectedData'?: string;
  }

  interface AppComparechart {
    'entity_to_compare': string;
    'entityid': string;
    'filter': string;
    'service_url': string;
    'type': string;
  }
  interface AppComparechartAttributes extends StencilHTMLAttributes {
    'entity_to_compare'?: string;
    'entityid'?: string;
    'filter'?: string;
    'service_url'?: string;
    'type'?: string;
  }

  interface AppRealchart {
    'entityid': string;
    'filter': string;
    'service_url': string;
    'type': string;
  }
  interface AppRealchartAttributes extends StencilHTMLAttributes {
    'entityid'?: string;
    'filter'?: string;
    'service_url'?: string;
    'type'?: string;
  }

  interface AppRoot {
    'id': string;
    'service_url': string;
    'type': string;
  }
  interface AppRootAttributes extends StencilHTMLAttributes {
    'id'?: string;
    'service_url'?: string;
    'type'?: string;
  }

  interface AppTable {
    'entityid': string;
    'filter': string;
    'page_url': string;
    'service_url': string;
    'type': string;
  }
  interface AppTableAttributes extends StencilHTMLAttributes {
    'entityid'?: string;
    'filter'?: string;
    'page_url'?: string;
    'service_url'?: string;
    'type'?: string;
  }

  interface AppWritecomponent {
    'page_url': string;
    'service_url': string;
  }
  interface AppWritecomponentAttributes extends StencilHTMLAttributes {
    'page_url'?: string;
    'service_url'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppCombobox': Components.AppCombobox;
    'AppComparechart': Components.AppComparechart;
    'AppRealchart': Components.AppRealchart;
    'AppRoot': Components.AppRoot;
    'AppTable': Components.AppTable;
    'AppWritecomponent': Components.AppWritecomponent;
  }

  interface StencilIntrinsicElements {
    'app-comboBox': Components.AppComboboxAttributes;
    'app-compareChart': Components.AppComparechartAttributes;
    'app-realChart': Components.AppRealchartAttributes;
    'app-root': Components.AppRootAttributes;
    'app-table': Components.AppTableAttributes;
    'app-writeComponent': Components.AppWritecomponentAttributes;
  }


  interface HTMLAppComboboxElement extends Components.AppCombobox, HTMLStencilElement {}
  var HTMLAppComboboxElement: {
    prototype: HTMLAppComboboxElement;
    new (): HTMLAppComboboxElement;
  };

  interface HTMLAppComparechartElement extends Components.AppComparechart, HTMLStencilElement {}
  var HTMLAppComparechartElement: {
    prototype: HTMLAppComparechartElement;
    new (): HTMLAppComparechartElement;
  };

  interface HTMLAppRealchartElement extends Components.AppRealchart, HTMLStencilElement {}
  var HTMLAppRealchartElement: {
    prototype: HTMLAppRealchartElement;
    new (): HTMLAppRealchartElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppTableElement extends Components.AppTable, HTMLStencilElement {}
  var HTMLAppTableElement: {
    prototype: HTMLAppTableElement;
    new (): HTMLAppTableElement;
  };

  interface HTMLAppWritecomponentElement extends Components.AppWritecomponent, HTMLStencilElement {}
  var HTMLAppWritecomponentElement: {
    prototype: HTMLAppWritecomponentElement;
    new (): HTMLAppWritecomponentElement;
  };

  interface HTMLElementTagNameMap {
    'app-comboBox': HTMLAppComboboxElement
    'app-compareChart': HTMLAppComparechartElement
    'app-realChart': HTMLAppRealchartElement
    'app-root': HTMLAppRootElement
    'app-table': HTMLAppTableElement
    'app-writeComponent': HTMLAppWritecomponentElement
  }

  interface ElementTagNameMap {
    'app-comboBox': HTMLAppComboboxElement;
    'app-compareChart': HTMLAppComparechartElement;
    'app-realChart': HTMLAppRealchartElement;
    'app-root': HTMLAppRootElement;
    'app-table': HTMLAppTableElement;
    'app-writeComponent': HTMLAppWritecomponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
